apiVersion: extensions/v1beta1 
kind: Ingress 
metadata: 
  name: bff-atcl
  namespace: test
  labels: 
    app.kubernetes.io/name: bff-atcl
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "128m" 
spec: 
  rules: 
  - host: bff.tbiz-atcl.net
    http: 
      paths: 
      - path: / 
        backend: 
          serviceName: bff-atcl
          servicePort: 8080 