apiVersion: v1 
kind: Service 
metadata: 
  name: bff-atcl
  namespace: test
spec: 
  selector: 
    app: bff-atcl
  type: ClusterIP 
  ports: 
    - name: http 
      port: 8080 
      protocol: TCP
      targetPort: 8080 